export const map = {
    id: 'ID',
    userId:'회원 ID',
    nickname: '닉네임',
    view: '조회수',
    createdAt: '날짜',
    subject: '제목',
    content: '내용',
    defId: '신고 당한 ID',
    compId: '신고한 ID',
    postId: '콘텐츠 ID',
    desc: '신고 이유',
    name: '이름',
    loginId:'로그인 ID',
    password:'로그인 방법',
    totalUsers: '전체 누적 가입자 수',
    totalActiveUsers: '전체 누석 활성 사용자 수',
    totalReturningUsers:'전체 누적 재방문자 수',
    newActiveUsers:'신규 활성 사용자 수',
    cumulativeUsers:'신규 가입자 수',
    cumulativeActiveUsers:'전체 활성 사용자 수',
    cumulativeReturningUsers:'재방문자 수',
    monthlyAvgNewActiveUsers:'평균 DAU (월)',
    registerDate: '가입 날짜',
    status: '회원 상태',
    posts: '포스트',
    comments: '댓글',
    likes: '좋아요',
    todayView: '오늘 공간 조회수',
    totalView: '누적 공간 조회수',
    contentId: '콘텐츠 ID',
    social: '소셜 로그인',
    contentAt: '게시 날짜',
    contentStatus: '콘텐츠 상태',
}